// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/appconfig.proto

package appconfig

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigRequest struct {
	AppName     string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	EnvCode     string `protobuf:"bytes,2,opt,name=env_code,json=envCode,proto3" json:"env_code,omitempty"`
	VersionName string `protobuf:"bytes,3,opt,name=version_name,json=versionName,proto3" json:"version_name,omitempty"`
	//app、环境、版本 维度下查询，如果key不为空，则只查这个key的value，否则查所有配置
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9ad451962778ea, []int{0}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ConfigRequest) GetEnvCode() string {
	if m != nil {
		return m.EnvCode
	}
	return ""
}

func (m *ConfigRequest) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *ConfigRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type BaseResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9ad451962778ea, []int{1}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BaseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Params struct {
	Keys                 string   `protobuf:"bytes,1,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9ad451962778ea, []int{2}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetKeys() string {
	if m != nil {
		return m.Keys
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9ad451962778ea, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfigRequest)(nil), "appconfig.ConfigRequest")
	proto.RegisterType((*BaseResponse)(nil), "appconfig.BaseResponse")
	proto.RegisterType((*Params)(nil), "appconfig.Params")
	proto.RegisterType((*Result)(nil), "appconfig.Result")
}

func init() { proto.RegisterFile("proto/appconfig.proto", fileDescriptor_7c9ad451962778ea) }

var fileDescriptor_7c9ad451962778ea = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0xfc, 0xfa, 0xb5, 0x49, 0xc9, 0x12, 0x10, 0x58, 0x20, 0x42, 0xc5, 0x01, 0x72, 0xe2, 0x54,
	0x10, 0x48, 0xdc, 0x4b, 0x90, 0x7a, 0x43, 0xc8, 0x07, 0xae, 0xd5, 0xd2, 0x2e, 0x55, 0xd5, 0xc6,
	0x36, 0xb6, 0x13, 0xa9, 0x3c, 0x01, 0x8f, 0x8d, 0x6c, 0x27, 0x25, 0xbd, 0xcd, 0xce, 0x78, 0x7f,
	0x66, 0x0c, 0xe7, 0x4a, 0x4b, 0x2b, 0xef, 0x50, 0xa9, 0xb9, 0x14, 0x9f, 0xab, 0xe5, 0xd8, 0xd7,
	0x2c, 0xd9, 0x11, 0xf9, 0x37, 0x1c, 0x15, 0x1e, 0x71, 0xfa, 0xaa, 0xc8, 0x58, 0x76, 0x09, 0x07,
	0xa8, 0xd4, 0x4c, 0x60, 0x49, 0x59, 0xef, 0xba, 0x77, 0x9b, 0xf0, 0x21, 0x2a, 0xf5, 0x8a, 0x25,
	0x39, 0x89, 0x44, 0x3d, 0x9b, 0xcb, 0x05, 0x65, 0xff, 0x83, 0x44, 0xa2, 0x2e, 0xe4, 0x82, 0xd8,
	0x0d, 0xa4, 0x35, 0x69, 0xb3, 0x92, 0x22, 0x74, 0xf6, 0xbd, 0x7c, 0xd8, 0x70, 0xbe, 0xfb, 0x04,
	0xfa, 0x6b, 0xda, 0x66, 0x03, 0xaf, 0x38, 0x98, 0x73, 0x48, 0x9f, 0xd1, 0x10, 0x27, 0xa3, 0xa4,
	0x30, 0xc4, 0x18, 0x0c, 0xfc, 0x6c, 0xb7, 0x36, 0xe2, 0x1e, 0xb3, 0x0c, 0x86, 0x25, 0x19, 0x83,
	0xcb, 0xdd, 0xca, 0xa6, 0x64, 0x67, 0x10, 0x91, 0xd6, 0x52, 0x37, 0xbb, 0x42, 0x91, 0x5f, 0x41,
	0xfc, 0x86, 0x1a, 0x4b, 0xe3, 0xa6, 0xad, 0x69, 0x6b, 0x1a, 0x13, 0x1e, 0xe7, 0xf7, 0x10, 0x73,
	0x32, 0xd5, 0xc6, 0x3a, 0xb5, 0x68, 0x7d, 0x44, 0xdc, 0x63, 0xc7, 0xbd, 0xa0, 0xc5, 0xb6, 0xc3,
	0xe1, 0x87, 0x9f, 0x1e, 0x24, 0x93, 0x36, 0x2d, 0x56, 0xc0, 0xf1, 0x94, 0x6c, 0x08, 0xec, 0x1d,
	0x37, 0x15, 0xb1, 0x6c, 0xfc, 0x17, 0xee, 0x5e, 0x90, 0xa3, 0x8b, 0x8e, 0xb2, 0x67, 0xf3, 0x09,
	0xd2, 0x29, 0xd9, 0x89, 0x52, 0xe1, 0x3d, 0x3b, 0xed, 0x3c, 0x0c, 0xb7, 0x8f, 0xba, 0x54, 0x38,
	0x38, 0xff, 0xf7, 0x11, 0xfb, 0xcf, 0x7b, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xc1, 0xf8,
	0x5c, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppconfigClient is the client API for Appconfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppconfigClient interface {
	//新服务
	GetConfigValue(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	//旧服务
	GetAppConfig(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Result, error)
}

type appconfigClient struct {
	cc *grpc.ClientConn
}

func NewAppconfigClient(cc *grpc.ClientConn) AppconfigClient {
	return &appconfigClient{cc}
}

func (c *appconfigClient) GetConfigValue(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/appconfig.Appconfig/GetConfigValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appconfigClient) GetAppConfig(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/appconfig.Appconfig/GetAppConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppconfigServer is the server API for Appconfig service.
type AppconfigServer interface {
	//新服务
	GetConfigValue(context.Context, *ConfigRequest) (*BaseResponse, error)
	//旧服务
	GetAppConfig(context.Context, *Params) (*Result, error)
}

// UnimplementedAppconfigServer can be embedded to have forward compatible implementations.
type UnimplementedAppconfigServer struct {
}

func (*UnimplementedAppconfigServer) GetConfigValue(ctx context.Context, req *ConfigRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigValue not implemented")
}
func (*UnimplementedAppconfigServer) GetAppConfig(ctx context.Context, req *Params) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppConfig not implemented")
}

func RegisterAppconfigServer(s *grpc.Server, srv AppconfigServer) {
	s.RegisterService(&_Appconfig_serviceDesc, srv)
}

func _Appconfig_GetConfigValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppconfigServer).GetConfigValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appconfig.Appconfig/GetConfigValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppconfigServer).GetConfigValue(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appconfig_GetAppConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppconfigServer).GetAppConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appconfig.Appconfig/GetAppConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppconfigServer).GetAppConfig(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

var _Appconfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appconfig.Appconfig",
	HandlerType: (*AppconfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigValue",
			Handler:    _Appconfig_GetConfigValue_Handler,
		},
		{
			MethodName: "GetAppConfig",
			Handler:    _Appconfig_GetAppConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/appconfig.proto",
}
